server:
  port: 8000 # 指定启动端口
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://xiaolvshu-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
